/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2;

import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author IT
 */
public class Leogram extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios = new ArrayList<>();
    Usuario usuarioActual;
    Usuario destinatario;
    ChatGrupal grupo;
    ChatPrivado privado;
    HiloMensaje hm;

    /**
     * Creates new form Leogram
     */
    public Leogram() {
        cargarUsuarios();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearUsuario = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombre_Crear = new javax.swing.JTextField();
        tf_apellido_Crear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ff_telefono_Crear = new javax.swing.JFormattedTextField();
        tf_usuario_Crear = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pf_contra_Crear = new javax.swing.JPasswordField();
        pf_confirmacion_Crear = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        bt_crearUsuario = new javax.swing.JButton();
        bt_cancelarCreacion = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        sp_conexion_Crear = new javax.swing.JSpinner();
        jd_ingreso = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_usuario_Ingresar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        bt_iniciarSesion = new javax.swing.JButton();
        bt_cancelarIngreso = new javax.swing.JButton();
        pf_contra_Ingresar = new javax.swing.JPasswordField();
        jd_solicitud = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_personas = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        bt_enviarSolicitud = new javax.swing.JButton();
        pm_amigos = new javax.swing.JPopupMenu();
        pmi_enviarMensaje = new javax.swing.JMenuItem();
        pmi_eliminarAmigo = new javax.swing.JMenuItem();
        pm_chats = new javax.swing.JPopupMenu();
        pmi_leerChat = new javax.swing.JMenuItem();
        jd_mensaje = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        bt_enviarMensaje = new javax.swing.JButton();
        pb1 = new javax.swing.JProgressBar();
        bt_enviarMensajeGrupal = new javax.swing.JButton();
        pm_grupos = new javax.swing.JPopupMenu();
        pmi_leerTodo = new javax.swing.JMenuItem();
        pmi_enviarGrupo = new javax.swing.JMenuItem();
        jd_leerMensajes = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_historial = new javax.swing.JTextArea();
        label_chat = new javax.swing.JLabel();
        jd_grupo = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        list_porAgregar = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        list_agregados = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tf_nombreGrupo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        panel_fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_amigos = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        bt_solicitud = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tree_chats = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jm_opciones = new javax.swing.JMenu();
        jmi_iniciarSesion = new javax.swing.JMenuItem();
        jmi_cerrarSesion = new javax.swing.JMenuItem();
        jmi_crearUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jd_crearUsuario.setTitle("Nuevo Usuario");

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("Nuevo Usuario");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero telefónico:");

        ff_telefono_Crear.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirmar ontraseña:");

        bt_crearUsuario.setBackground(new java.awt.Color(0, 0, 0));
        bt_crearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        bt_crearUsuario.setText("Crear Usuario");
        bt_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearUsuarioActionPerformed(evt);
            }
        });

        bt_cancelarCreacion.setBackground(new java.awt.Color(255, 0, 0));
        bt_cancelarCreacion.setForeground(new java.awt.Color(255, 255, 255));
        bt_cancelarCreacion.setText("Cancelar");
        bt_cancelarCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarCreacionActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Calidad de conexión a WIFI:");

        sp_conexion_Crear.setModel(new javax.swing.SpinnerNumberModel(5, 1, 5, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pf_contra_Crear, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ff_telefono_Crear, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_nombre_Crear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel8)
                    .addComponent(sp_conexion_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_cancelarCreacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_crearUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tf_apellido_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tf_usuario_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_confirmacion_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nombre_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_apellido_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_usuario_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ff_telefono_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pf_contra_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pf_confirmacion_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_crearUsuario)
                            .addComponent(bt_cancelarCreacion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_conexion_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_crearUsuarioLayout = new javax.swing.GroupLayout(jd_crearUsuario.getContentPane());
        jd_crearUsuario.getContentPane().setLayout(jd_crearUsuarioLayout);
        jd_crearUsuarioLayout.setHorizontalGroup(
            jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_crearUsuarioLayout.setVerticalGroup(
            jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jd_ingreso.setTitle("Ingreso");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Inicio de Sesión");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Usuario:");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Contraseña:");

        bt_iniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        bt_iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        bt_iniciarSesion.setText("Iniciar Sesión");
        bt_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_iniciarSesionActionPerformed(evt);
            }
        });

        bt_cancelarIngreso.setBackground(new java.awt.Color(255, 0, 0));
        bt_cancelarIngreso.setForeground(new java.awt.Color(255, 255, 255));
        bt_cancelarIngreso.setText("Cancelar");
        bt_cancelarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(128, 128, 128))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_cancelarIngreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_iniciarSesion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pf_contra_Ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_usuario_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_usuario_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pf_contra_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_iniciarSesion)
                    .addComponent(bt_cancelarIngreso))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_ingresoLayout = new javax.swing.GroupLayout(jd_ingreso.getContentPane());
        jd_ingreso.getContentPane().setLayout(jd_ingresoLayout);
        jd_ingresoLayout.setHorizontalGroup(
            jd_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_ingresoLayout.setVerticalGroup(
            jd_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_solicitud.setTitle("Envío de solicitud de amistad");

        list_personas.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(list_personas);

        jLabel15.setText("Personas:");

        bt_enviarSolicitud.setText("Enviar solicitud");
        bt_enviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_solicitudLayout = new javax.swing.GroupLayout(jd_solicitud.getContentPane());
        jd_solicitud.getContentPane().setLayout(jd_solicitudLayout);
        jd_solicitudLayout.setHorizontalGroup(
            jd_solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_solicitudLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jd_solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_enviarSolicitud)
                    .addGroup(jd_solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jd_solicitudLayout.setVerticalGroup(
            jd_solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_solicitudLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_enviarSolicitud)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pmi_enviarMensaje.setText("Enviar mensaje");
        pmi_enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmi_enviarMensajeActionPerformed(evt);
            }
        });
        pm_amigos.add(pmi_enviarMensaje);

        pmi_eliminarAmigo.setText("Eliminar amigo");
        pmi_eliminarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmi_eliminarAmigoActionPerformed(evt);
            }
        });
        pm_amigos.add(pmi_eliminarAmigo);

        pmi_leerChat.setText("Leer todo el chat");
        pmi_leerChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmi_leerChatActionPerformed(evt);
            }
        });
        pm_chats.add(pmi_leerChat);

        jd_mensaje.setTitle("Enviar Mensaje");

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane4.setViewportView(ta_mensaje);

        bt_enviarMensaje.setText("Enviar Mensaje");
        bt_enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarMensajeActionPerformed(evt);
            }
        });

        pb1.setBackground(new java.awt.Color(255, 153, 0));
        pb1.setForeground(new java.awt.Color(255, 0, 0));
        pb1.setBorderPainted(false);

        bt_enviarMensajeGrupal.setText("Enviar Mensaje Grupal");
        bt_enviarMensajeGrupal.setEnabled(false);
        bt_enviarMensajeGrupal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarMensajeGrupalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_mensajeLayout = new javax.swing.GroupLayout(jd_mensaje.getContentPane());
        jd_mensaje.getContentPane().setLayout(jd_mensajeLayout);
        jd_mensajeLayout.setHorizontalGroup(
            jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mensajeLayout.createSequentialGroup()
                .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mensajeLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(pb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_mensajeLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(bt_enviarMensaje))
                    .addGroup(jd_mensajeLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(bt_enviarMensajeGrupal)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jd_mensajeLayout.setVerticalGroup(
            jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mensajeLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_enviarMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_enviarMensajeGrupal)
                .addContainerGap())
        );

        pmi_leerTodo.setText("Leer todo");
        pmi_leerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmi_leerTodoActionPerformed(evt);
            }
        });
        pm_grupos.add(pmi_leerTodo);

        pmi_enviarGrupo.setText("Leer todo");
        pmi_enviarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmi_enviarGrupoActionPerformed(evt);
            }
        });
        pm_grupos.add(pmi_enviarGrupo);

        jd_leerMensajes.setTitle("Historial de chat");

        ta_historial.setEditable(false);
        ta_historial.setColumns(20);
        ta_historial.setRows(5);
        jScrollPane5.setViewportView(ta_historial);

        label_chat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_chat.setText("jLabel16");

        javax.swing.GroupLayout jd_leerMensajesLayout = new javax.swing.GroupLayout(jd_leerMensajes.getContentPane());
        jd_leerMensajes.getContentPane().setLayout(jd_leerMensajesLayout);
        jd_leerMensajesLayout.setHorizontalGroup(
            jd_leerMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_leerMensajesLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jd_leerMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_chat)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jd_leerMensajesLayout.setVerticalGroup(
            jd_leerMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_leerMensajesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_chat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        list_porAgregar.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(list_porAgregar);

        list_agregados.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(list_agregados);

        jButton2.setText("Agregar =>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<=Quitar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Nombre grupo:");

        javax.swing.GroupLayout jd_grupoLayout = new javax.swing.GroupLayout(jd_grupo.getContentPane());
        jd_grupo.getContentPane().setLayout(jd_grupoLayout);
        jd_grupoLayout.setHorizontalGroup(
            jd_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_grupoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jd_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_grupoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_grupoLayout.createSequentialGroup()
                        .addGroup(jd_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_grupoLayout.createSequentialGroup()
                                .addComponent(tf_nombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_grupoLayout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGap(27, 27, 27))))
        );
        jd_grupoLayout.setVerticalGroup(
            jd_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_grupoLayout.createSequentialGroup()
                .addGroup(jd_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_grupoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jd_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_grupoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addGroup(jd_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_grupoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33))
                    .addGroup(jd_grupoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEOGRAM");

        panel_fondo.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Sistema de Mensajería");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("LEOGRAM");

        list_amigos.setModel(new DefaultListModel());
        list_amigos.setEnabled(false);
        list_amigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_amigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_amigos);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Amigos:");

        bt_solicitud.setBackground(new java.awt.Color(0, 0, 255));
        bt_solicitud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_solicitud.setForeground(new java.awt.Color(255, 255, 255));
        bt_solicitud.setText("Enviar solicitud de amistad");
        bt_solicitud.setEnabled(false);
        bt_solicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_solicitudActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Chats");
        tree_chats.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree_chats.setEnabled(false);
        tree_chats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree_chatsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tree_chats);

        jButton1.setText("Crear grupo");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Cerrar sesión y volver a abrirla después de");

        jLabel18.setText("aceptar una solicitud");

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(30, 30, 30)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(bt_solicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(81, 81, 81))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel18))
                .addGap(7, 7, 7)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_solicitud)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18))
        );

        jm_opciones.setText("Opciones");

        jmi_iniciarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmi_iniciarSesion.setText("Iniciar Sesión");
        jmi_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_iniciarSesionActionPerformed(evt);
            }
        });
        jm_opciones.add(jmi_iniciarSesion);

        jmi_cerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmi_cerrarSesion.setText("Cerrar Sesión");
        jmi_cerrarSesion.setEnabled(false);
        jmi_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cerrarSesionActionPerformed(evt);
            }
        });
        jm_opciones.add(jmi_cerrarSesion);

        jmi_crearUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmi_crearUsuario.setText("Crear nuevo Usuario");
        jmi_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearUsuarioActionPerformed(evt);
            }
        });
        jm_opciones.add(jmi_crearUsuario);

        jMenuItem1.setText("Eliminar Cuenta");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_opciones.add(jMenuItem1);

        menuBar.add(jm_opciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearUsuarioActionPerformed
        try {
            String nombre = tf_nombre_Crear.getText().trim();
            String apellido = tf_apellido_Crear.getText().trim();
            int numeroTelefonico = Integer.parseInt(ff_telefono_Crear.getValue().toString());
            String usuario = tf_usuario_Crear.getText().trim();
            String contraseña = pf_contra_Crear.getText().trim();
            String confirmacion = pf_confirmacion_Crear.getText().trim();
            int calidad = Integer.parseInt(sp_conexion_Crear.getValue().toString());

            if (!nombre.equals("") && !apellido.equals("") && !usuario.equals("") && !contraseña.equals("")) { //Confirmamos que no haya campos vacíos
                if (usuarioValido(usuario)) { //Confirmamos que el usuario sea único
                    if (contraseña.equals(confirmacion)) { //Verificamos la confirmación de la contraseña
                        Usuario user = new Usuario(usuario, contraseña, calidad, nombre, apellido, numeroTelefonico);
                        usuarios.add(user);
                        usuarioActual = user;
                        jd_crearUsuario.setVisible(false);
                        limpiarCreacion();
                        ingresar();
                        escribirUsuarios();
                    } else {
                        JOptionPane.showMessageDialog(jd_crearUsuario, "Error al confirmar la contraseña.", "Confirmación fallida", 0);
                    }
                } else {
                    JOptionPane.showMessageDialog(jd_crearUsuario, "El usuario ingresado ya existe.", "Usuario inválido", 0);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_crearUsuarioActionPerformed

    private void bt_cancelarCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarCreacionActionPerformed
        jd_crearUsuario.setVisible(false);
        limpiarCreacion();
    }//GEN-LAST:event_bt_cancelarCreacionActionPerformed

    private void bt_cancelarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarIngresoActionPerformed
        jd_ingreso.setVisible(false);
        limpiarIngreso();
    }//GEN-LAST:event_bt_cancelarIngresoActionPerformed

    private void bt_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_iniciarSesionActionPerformed
        try {
            String usuario = tf_usuario_Ingresar.getText().trim();
            String contraseña = pf_contra_Ingresar.getText().trim();
            boolean flag = false;
            for (Usuario u : usuarios) {
                if (u.getUsuario().equals(usuario)) {
                    if (u.getContraseña().equals(contraseña)) {
                        usuarioActual = u;
                        jd_ingreso.setVisible(false);//Ocultamos la subventana
                        limpiarIngreso();
                        ingresar(); //Ingresamos al sistema
                        flag = true;
                        break;
                    }
                }
            }
            if (!flag) {
                JOptionPane.showMessageDialog(jd_ingreso, "El usuario y/o contraseña son incorrectos.", "Ingreso fallido", 0);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_iniciarSesionActionPerformed

    private void jmi_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_iniciarSesionActionPerformed
        jd_ingreso.pack();
        jd_ingreso.setLocationRelativeTo(this);
        jd_ingreso.setModal(true);
        jd_ingreso.setVisible(true);
    }//GEN-LAST:event_jmi_iniciarSesionActionPerformed

    private void jmi_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearUsuarioActionPerformed
        jd_crearUsuario.pack();
        jd_crearUsuario.setLocationRelativeTo(this);
        jd_crearUsuario.setModal(true);
        jd_crearUsuario.setVisible(true);
    }//GEN-LAST:event_jmi_crearUsuarioActionPerformed

    private void bt_solicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_solicitudActionPerformed

        DefaultListModel lmodel = (DefaultListModel) list_personas.getModel();
        lmodel.removeAllElements();
        for (Usuario usuario : usuarios) {
            if (!usuario.equals(usuarioActual) && !usuarioActual.getAmigos().contains(usuario) && !usuario.getSolicitudes().contains(usuarioActual)) {
                lmodel.addElement(usuario);
            }
        }
        list_personas.setModel(lmodel);

        jd_solicitud.pack();
        jd_solicitud.setLocationRelativeTo(this);
        jd_solicitud.setModal(true);
        jd_solicitud.setVisible(true);
    }//GEN-LAST:event_bt_solicitudActionPerformed

    private void jmi_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cerrarSesionActionPerformed
        list_personas.setModel(new DefaultListModel());
        tree_chats.setModel(new DefaultTreeModel(new DefaultMutableTreeNode("Chats")));
        cambiarEstado(true);
        usuarioActual = null;
        escribirUsuarios();
    }//GEN-LAST:event_jmi_cerrarSesionActionPerformed

    private void bt_enviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarSolicitudActionPerformed
        if (list_personas.getSelectedIndex() >= 0) {
            DefaultListModel lmodel = (DefaultListModel) list_personas.getModel();
            Usuario u = (Usuario) lmodel.getElementAt(list_personas.getSelectedIndex());
            u.getSolicitudes().add(usuarioActual);
            JOptionPane.showMessageDialog(jd_solicitud, "Solicitud enviada.", "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
            jd_solicitud.setVisible(false);
        }
    }//GEN-LAST:event_bt_enviarSolicitudActionPerformed

    private void list_amigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_amigosMouseClicked
        if (evt.isMetaDown()) {
            if (list_amigos.getSelectedIndex() >= 0) {
                pm_amigos.show(evt.getComponent(), evt.getX(), evt.getY());
                DefaultListModel lmodel = (DefaultListModel) list_amigos.getModel();
                destinatario = (Usuario) lmodel.getElementAt(list_amigos.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_list_amigosMouseClicked

    private void pmi_eliminarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmi_eliminarAmigoActionPerformed
        DefaultListModel lmodel = (DefaultListModel) list_amigos.getModel();
        Usuario amigo = (Usuario) lmodel.getElementAt(list_amigos.getSelectedIndex());
        destinatario.getAmigos().remove(usuarioActual);
        usuarioActual.getAmigos().remove(amigo);
        lmodel.removeElement(destinatario);
        list_amigos.setModel(lmodel);
        escribirUsuarios();
    }//GEN-LAST:event_pmi_eliminarAmigoActionPerformed

    private void bt_enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarMensajeActionPerformed
        if (destinatario != null) {
            boolean flag = false;
            ChatPrivado c = null;

            for (Chat chat : usuarioActual.getChats()) {
                if (chat instanceof ChatPrivado) {
                    c = (ChatPrivado) chat;
                    if (c.getPrimero().equals(destinatario) || c.getSegundo().equals(destinatario)) {
                        flag = true;
                        break;
                    }
                }
            }
            if (!flag) {
                c = new ChatPrivado(usuarioActual, destinatario);
                usuarioActual.getChats().add(c);
                destinatario.getChats().add(c);
            }
            try {
                double d = usuarioActual.ENVIAR(destinatario);
                hm = new HiloMensaje(
                        d,
                        pb1,
                        jd_mensaje
                );
                hm.start();

                c.getMensajes().add(
                        new Mensaje(usuarioActual.getUsuario() + ": " + ta_mensaje.getText(), new Date())
                );
            } catch (Exception e) {
                e.printStackTrace();
            }
            escribirUsuarios();
            ta_mensaje.setText("");
            cargarArbolChats();
        }
    }//GEN-LAST:event_bt_enviarMensajeActionPerformed

    private void pmi_enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmi_enviarMensajeActionPerformed

        bt_enviarMensaje.setEnabled(true);
        bt_enviarMensajeGrupal.setEnabled(false);

        ta_mensaje.setText("");
        jd_mensaje.pack();
        jd_mensaje.setModal(true);
        jd_mensaje.setLocationRelativeTo(this);
        jd_mensaje.setVisible(true);
    }//GEN-LAST:event_pmi_enviarMensajeActionPerformed

    private void tree_chatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_chatsMouseClicked
        if (evt.isMetaDown()) {

            int row = tree_chats.getClosestRowForLocation(evt.getX(), evt.getY());
            tree_chats.setSelectionRow(row);

            Object node = tree_chats.getSelectionPath().getLastPathComponent();
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) node;

            if (nodo.getUserObject() instanceof ChatPrivado) {
                privado = (ChatPrivado) nodo.getUserObject();

                pm_chats.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (nodo.getUserObject() instanceof ChatGrupal) {
                grupo = (ChatGrupal) nodo.getUserObject();

                pm_grupos.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tree_chatsMouseClicked

    private void pmi_leerChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmi_leerChatActionPerformed
        label_chat.setText(privado.toString());
        ta_historial.setText("");

        for (Mensaje mensaje : privado.getMensajes()) {
            if (mensaje.getContenido().contains(usuarioActual.getUsuario())) {
                mensaje.setLeido(true);
            }
            ta_historial.append(mensaje.toString());
        }

        jd_leerMensajes.pack();
        jd_leerMensajes.setModal(true);
        jd_leerMensajes.setLocationRelativeTo(this);
        jd_leerMensajes.setVisible(true);

    }//GEN-LAST:event_pmi_leerChatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel m1 = (DefaultListModel) list_porAgregar.getModel();
        DefaultListModel m2 = (DefaultListModel) list_agregados.getModel();
        m1.removeAllElements();
        m2.removeAllElements();

        for (Usuario amigo : usuarioActual.getAmigos()) {
            m1.addElement(amigo);
        }
        list_porAgregar.setModel(m1);
        list_agregados.setModel(m2);

        tf_nombreGrupo.setText("");

        jd_grupo.pack();
        jd_grupo.setModal(true);
        jd_grupo.setLocationRelativeTo(this);
        jd_grupo.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (list_porAgregar.getSelectedIndex() >= 0) {
            DefaultListModel m1 = (DefaultListModel) list_porAgregar.getModel();
            DefaultListModel m2 = (DefaultListModel) list_agregados.getModel();
            Usuario u = (Usuario) m1.getElementAt(list_porAgregar.getSelectedIndex());
            m2.addElement(u);
            m1.removeElement(u);
            list_agregados.setModel(m2);
            list_porAgregar.setModel(m1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (list_agregados.getSelectedIndex() >= 0) {
            DefaultListModel m1 = (DefaultListModel) list_agregados.getModel();
            DefaultListModel m2 = (DefaultListModel) list_porAgregar.getModel();
            Usuario u = (Usuario) m1.getElementAt(list_agregados.getSelectedIndex());
            m2.addElement(u);
            m1.removeElement(u);
            list_porAgregar.setModel(m2);
            list_agregados.setModel(m1);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String nombre = tf_nombreGrupo.getText();

            ChatGrupal cg = new ChatGrupal(nombre, usuarioActual);
            DefaultListModel m1 = (DefaultListModel) list_agregados.getModel();
            for (int i = 0; i < m1.getSize(); i++) {
                try {
                    Usuario p = (Usuario) m1.getElementAt(i);
                    cg.getMiembros().add(p);
                    p.getChats().add(cg);
                } catch (Exception e) {
                }
            }
            jd_grupo.setVisible(false);

            escribirUsuarios();
            cargarArbolChats();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pmi_leerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmi_leerTodoActionPerformed
        label_chat.setText(grupo.toString());
        ta_historial.setText("");

        for (Mensaje mensaje : grupo.getMensajes()) {
            if (mensaje.getContenido().contains(usuarioActual.getUsuario())) {
                mensaje.setLeido(true);
            }
            ta_historial.append(mensaje.toString());
        }

        jd_leerMensajes.pack();
        jd_leerMensajes.setModal(true);
        jd_leerMensajes.setLocationRelativeTo(this);
        jd_leerMensajes.setVisible(true);

    }//GEN-LAST:event_pmi_leerTodoActionPerformed

    private void pmi_enviarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmi_enviarGrupoActionPerformed
        bt_enviarMensaje.setEnabled(false);
        bt_enviarMensajeGrupal.setEnabled(true);

        ta_mensaje.setText("");
        jd_mensaje.pack();
        jd_mensaje.setModal(true);
        jd_mensaje.setLocationRelativeTo(this);
        jd_mensaje.setVisible(true);
    }//GEN-LAST:event_pmi_enviarGrupoActionPerformed

    private void bt_enviarMensajeGrupalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarMensajeGrupalActionPerformed

        try {
            for (Usuario usuario : grupo.getMiembros()) {
                if (!usuario.equals(usuarioActual)) {

                    double d = usuarioActual.ENVIAR(usuario);
                    hm = new HiloMensaje(
                            d,
                            pb1,
                            jd_mensaje
                    );
                    hm.start();
                }
            }

            grupo.getMensajes().add(
                    new Mensaje(usuarioActual.getUsuario() + ": " + ta_mensaje.getText(), new Date())
            );
        } catch (Exception e) {
            e.printStackTrace();
        }
        escribirUsuarios();
        ta_mensaje.setText("");
        cargarArbolChats();

    }//GEN-LAST:event_bt_enviarMensajeGrupalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (usuarioActual != null) {
            usuarios.remove(usuarioActual);
            for (Usuario usuario : usuarios) {
                usuario.getAmigos().remove(usuarioActual);
                usuario.getSolicitudes().remove(usuarioActual);
            }
            cambiarEstado(false);
            list_personas.setModel(new DefaultListModel());
            tree_chats.setModel(new DefaultTreeModel(new DefaultMutableTreeNode("Chats")));
            cambiarEstado(true);
            usuarioActual = null;
            escribirUsuarios();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leogram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelarCreacion;
    private javax.swing.JButton bt_cancelarIngreso;
    private javax.swing.JButton bt_crearUsuario;
    private javax.swing.JButton bt_enviarMensaje;
    private javax.swing.JButton bt_enviarMensajeGrupal;
    private javax.swing.JButton bt_enviarSolicitud;
    private javax.swing.JButton bt_iniciarSesion;
    private javax.swing.JButton bt_solicitud;
    private javax.swing.JFormattedTextField ff_telefono_Crear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JDialog jd_crearUsuario;
    private javax.swing.JDialog jd_grupo;
    private javax.swing.JDialog jd_ingreso;
    private javax.swing.JDialog jd_leerMensajes;
    private javax.swing.JDialog jd_mensaje;
    private javax.swing.JDialog jd_solicitud;
    private javax.swing.JMenu jm_opciones;
    private javax.swing.JMenuItem jmi_cerrarSesion;
    private javax.swing.JMenuItem jmi_crearUsuario;
    private javax.swing.JMenuItem jmi_iniciarSesion;
    private javax.swing.JLabel label_chat;
    private javax.swing.JList<String> list_agregados;
    private javax.swing.JList<String> list_amigos;
    private javax.swing.JList<String> list_personas;
    private javax.swing.JList<String> list_porAgregar;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JPasswordField pf_confirmacion_Crear;
    private javax.swing.JPasswordField pf_contra_Crear;
    private javax.swing.JPasswordField pf_contra_Ingresar;
    private javax.swing.JPopupMenu pm_amigos;
    private javax.swing.JPopupMenu pm_chats;
    private javax.swing.JPopupMenu pm_grupos;
    private javax.swing.JMenuItem pmi_eliminarAmigo;
    private javax.swing.JMenuItem pmi_enviarGrupo;
    private javax.swing.JMenuItem pmi_enviarMensaje;
    private javax.swing.JMenuItem pmi_leerChat;
    private javax.swing.JMenuItem pmi_leerTodo;
    private javax.swing.JSpinner sp_conexion_Crear;
    private javax.swing.JTextArea ta_historial;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextField tf_apellido_Crear;
    private javax.swing.JTextField tf_nombreGrupo;
    private javax.swing.JTextField tf_nombre_Crear;
    private javax.swing.JTextField tf_usuario_Crear;
    private javax.swing.JTextField tf_usuario_Ingresar;
    private javax.swing.JTree tree_chats;
    // End of variables declaration//GEN-END:variables

    private void limpiarCreacion() {
        tf_nombre_Crear.setText("");
        tf_apellido_Crear.setText("");
        tf_usuario_Crear.setText("");
        ff_telefono_Crear.setText("");
        pf_contra_Crear.setText("");
        pf_confirmacion_Crear.setText("");
        sp_conexion_Crear.setValue(5);
    }

    private void cargarUsuarios() {
        try {
            FileInputStream fis = null;
            ObjectInputStream ois = null;
            File file = new File("./Usuarios.leo");
            if (file.exists()) {
                try {
                    fis = new FileInputStream(file);
                    ois = new ObjectInputStream(fis);
                    Usuario usuario;
                    usuarios = new ArrayList<>();
                    while ((usuario = (Usuario) ois.readObject()) != null) {
                        usuarios.add(usuario);
                    }

                } catch (EOFException | ClassNotFoundException ex) {
                } catch (IOException ex) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Error con archivo de Usuarios.leo al cargar");
                } finally {
                    try {
                        ois.close();
                        fis.close();
                    } catch (IOException ex) {
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void escribirUsuarios() {
        FileOutputStream fos = null;
        ObjectOutputStream oos = null;
        try {
            File file = new File("./Usuarios.leo");
            fos = new FileOutputStream(file, false);
            oos = new ObjectOutputStream(fos);

            for (Usuario usuario : usuarios) {
                oos.writeObject(usuario);
            }

        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error con archivo de Usuarios.leo al escribir");
        } finally {
            try {
                oos.close();
                fos.close();
            } catch (IOException ex) {
            }
        }
    }

    private void ingresar() {
        cambiarEstado(false);
        usuarioActual.mostrarSolicitudes(this);
        cargarArbolChats();
        cargarListaAmigos();
    }

    private void limpiarIngreso() {
        tf_usuario_Ingresar.setText("");
        pf_contra_Ingresar.setText("");
    }

    private boolean usuarioValido(String usuario) {
        boolean valido = true;
        for (Usuario u : usuarios) {
            if (u.getUsuario().equals(usuario)) {
                valido = false;
                break;
            }
        }
        return valido;
    }

    private void cargarListaAmigos() {
        if (usuarioActual != null) {
            DefaultListModel lmodel = new DefaultListModel();//(DefaultListModel) list_amigos.getModel();
            //lmodel.removeAllElements();
            for (Usuario amigo : usuarioActual.getAmigos()) {
                System.out.println(amigo);
                lmodel.addElement(amigo);
            }
            list_amigos.setModel(lmodel);
            list_amigos.setModel(lmodel);
        }
    }

    private void cambiarEstado(boolean b) {
        jmi_crearUsuario.setEnabled(b);
        jmi_iniciarSesion.setEnabled(b);
        jmi_cerrarSesion.setEnabled(!b);
        list_amigos.setEnabled(!b);
        bt_solicitud.setEnabled(!b);
        tree_chats.setEnabled(!b);
        jButton1.setEnabled(!b);
        jMenuItem1.setEnabled(!b);
    }

    private void cargarArbolChats() {
        if (usuarioActual != null) {
            DefaultTreeModel tmodel = new DefaultTreeModel(
                    new DefaultMutableTreeNode("Chats " + usuarioActual.getUsuario())
            );
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) tmodel.getRoot();
            for (Chat chat : usuarioActual.getChats()) {
                root.add(
                        new DefaultMutableTreeNode(chat)
                );
            }
            tree_chats.setModel(tmodel);
        }
    }

}
